from PyQt5 import QtCore, QtGui, QtWidgets


class UiTest(object):
    def setupUi(self, Test):
        Test.setObjectName("Test")
        Test.resize(1200, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Test.sizePolicy().hasHeightForWidth())
        Test.setSizePolicy(sizePolicy)
        Test.setMinimumSize(QtCore.QSize(945, 545))
        Test.setMaximumSize(QtCore.QSize(1200, 700))
        Test.setSizeIncrement(QtCore.QSize(0, 0))
        Test.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lblclinicname = QtWidgets.QLabel(Test)
        self.lblclinicname.setGeometry(QtCore.QRect(450, 10, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        font.setUnderline(False)
        self.lblclinicname.setFont(font)
        self.lblclinicname.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblclinicname.setAlignment(QtCore.Qt.AlignCenter)
        self.lblclinicname.setObjectName("lblclinicname")
        self.line = QtWidgets.QFrame(Test)
        self.line.setGeometry(QtCore.QRect(0, 40, 1201, 21))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.lbllabname = QtWidgets.QLabel(Test)
        self.lbllabname.setGeometry(QtCore.QRect(1100, 130, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lbllabname.setFont(font)
        self.lbllabname.setObjectName("lbllabname")
        self.lineEditlabname = QtWidgets.QLineEdit(Test)
        self.lineEditlabname.setGeometry(QtCore.QRect(950, 130, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEditlabname.setFont(font)
        self.lineEditlabname.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditlabname.setObjectName("lineEditlabname")
        self.lbltypelab = QtWidgets.QLabel(Test)
        self.lbltypelab.setGeometry(QtCore.QRect(1100, 90, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lbltypelab.setFont(font)
        self.lbltypelab.setObjectName("lbltypelab")
        self.comboBoxtypelab = QtWidgets.QComboBox(Test)
        self.comboBoxtypelab.setGeometry(QtCore.QRect(950, 90, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.comboBoxtypelab.setFont(font)
        self.comboBoxtypelab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxtypelab.setObjectName("comboBoxtypelab")
        self.lineEditlabname_2 = QtWidgets.QLineEdit(Test)
        self.lineEditlabname_2.setGeometry(QtCore.QRect(670, 130, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEditlabname_2.setFont(font)
        self.lineEditlabname_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditlabname_2.setObjectName("lineEditlabname_2")
        self.lbllabname_2 = QtWidgets.QLabel(Test)
        self.lbllabname_2.setGeometry(QtCore.QRect(820, 130, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lbllabname_2.setFont(font)
        self.lbllabname_2.setObjectName("lbllabname_2")
        self.lineEditlabname_3 = QtWidgets.QLineEdit(Test)
        self.lineEditlabname_3.setGeometry(QtCore.QRect(440, 130, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEditlabname_3.setFont(font)
        self.lineEditlabname_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditlabname_3.setObjectName("lineEditlabname_3")
        self.lbllabname_3 = QtWidgets.QLabel(Test)
        self.lbllabname_3.setGeometry(QtCore.QRect(590, 130, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lbllabname_3.setFont(font)
        self.lbllabname_3.setObjectName("lbllabname_3")
        self.pushButtondelete = QtWidgets.QPushButton(Test)
        self.pushButtondelete.setGeometry(QtCore.QRect(300, 120, 91, 28))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        self.pushButtondelete.setFont(font)
        self.pushButtondelete.setObjectName("pushButtondelete")
        self.pushButtonregister = QtWidgets.QPushButton(Test)
        self.pushButtonregister.setGeometry(QtCore.QRect(80, 120, 91, 28))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        self.pushButtonregister.setFont(font)
        self.pushButtonregister.setObjectName("pushButtonregister")
        self.pushButtonedit = QtWidgets.QPushButton(Test)
        self.pushButtonedit.setGeometry(QtCore.QRect(190, 120, 91, 28))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        self.pushButtonedit.setFont(font)
        self.pushButtonedit.setObjectName("pushButtonedit")
        self.tableWidgetlabregister = QtWidgets.QTableWidget(Test)
        self.tableWidgetlabregister.setGeometry(QtCore.QRect(340, 240, 531, 405))
        self.tableWidgetlabregister.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidgetlabregister.setObjectName("tableWidgetlabregister")
        self.tableWidgetlabregister.setColumnCount(4)
        self.tableWidgetlabregister.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetlabregister.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetlabregister.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetlabregister.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetlabregister.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetlabregister.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetlabregister.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetlabregister.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetlabregister.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetlabregister.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetlabregister.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetlabregister.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetlabregister.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetlabregister.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetlabregister.setHorizontalHeaderItem(3, item)
        self.label_3 = QtWidgets.QLabel(Test)
        self.label_3.setGeometry(QtCore.QRect(10, 650, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(7)
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Test)
        self.label_5.setGeometry(QtCore.QRect(20, 590, 101, 81))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        font.setUnderline(False)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Test)
        QtCore.QMetaObject.connectSlotsByName(Test)

    def retranslateUi(self, Test):
        _translate = QtCore.QCoreApplication.translate
        Test.setWindowTitle(_translate("Test", "ثبت آزمایش"))
        self.lblclinicname.setText(_translate("Test", "درمانگاه دانشگاه پدافندهوایی خاتم الانبیاء(ص)"))
        self.lbllabname.setText(_translate("Test", "نام آزمایش:"))
        self.lbltypelab.setText(_translate("Test", "نوع آزمایش:"))
        self.lbllabname_2.setText(_translate("Test", "واحد اندازه گیری:"))
        self.lbllabname_3.setText(_translate("Test", "رنج نرمال:"))
        self.pushButtondelete.setText(_translate("Test", "حذف"))
        self.pushButtonregister.setText(_translate("Test", "ثبت"))
        self.pushButtonedit.setText(_translate("Test", "ویرایش"))
        item = self.tableWidgetlabregister.verticalHeaderItem(0)
        item.setText(_translate("Test", "1"))
        item = self.tableWidgetlabregister.verticalHeaderItem(1)
        item.setText(_translate("Test", "2"))
        item = self.tableWidgetlabregister.verticalHeaderItem(2)
        item.setText(_translate("Test", "3"))
        item = self.tableWidgetlabregister.verticalHeaderItem(3)
        item.setText(_translate("Test", "4"))
        item = self.tableWidgetlabregister.verticalHeaderItem(4)
        item.setText(_translate("Test", "5"))
        item = self.tableWidgetlabregister.verticalHeaderItem(5)
        item.setText(_translate("Test", "6"))
        item = self.tableWidgetlabregister.verticalHeaderItem(6)
        item.setText(_translate("Test", "7"))
        item = self.tableWidgetlabregister.verticalHeaderItem(7)
        item.setText(_translate("Test", "8"))
        item = self.tableWidgetlabregister.verticalHeaderItem(8)
        item.setText(_translate("Test", "9"))
        item = self.tableWidgetlabregister.verticalHeaderItem(9)
        item.setText(_translate("Test", "10"))
        item = self.tableWidgetlabregister.horizontalHeaderItem(0)
        item.setText(_translate("Test", "Test Name"))
        item = self.tableWidgetlabregister.horizontalHeaderItem(1)
        item.setText(_translate("Test", "Result"))
        item = self.tableWidgetlabregister.horizontalHeaderItem(2)
        item.setText(_translate("Test", "Units"))
        item = self.tableWidgetlabregister.horizontalHeaderItem(3)
        item.setText(_translate("Test", "Reference Range"))
        self.label_3.setText(_translate("Test", "سازنده اثر: شرکت نرم افزاری XERXESS"))
        self.label_5.setText(_translate("Test", "<html><head/><body><p><img src=\":/newPrefix/image/xerxes.png\"/></p></body></html>"))
import resource_clinic_rc
